cd c:\

@echo off

COLOR 02

echo BILL GATES HAS BEEN DISCOVERED ON THIS PC
echo BILL GATES HAS BEEN DISCOVERED ON THIS PC
echo BILL GATES HAS BEEN DISCOVERED ON THIS PC
echo BILL GATES HAS BEEN DISCOVERED ON THIS PC
echo BILL GATES HAS BEEN DISCOVERED ON THIS PC
echo BILL GATES HAS BEEN DISCOVERED ON THIS PC
echo BILL GATES HAS BEEN DISCOVERED ON THIS PC
echo BILL GATES HAS BEEN DISCOVERED ON THIS PC
echo BILL GATES HAS BEEN DISCOVERED ON THIS PC
echo BILL GATES HAS BEEN DISCOVERED ON THIS PC
echo BILL GATES HAS BEEN DISCOVERED ON THIS PC
echo BILL GATES HAS BEEN DISCOVERED ON THIS PC
echo BILL GATES HAS BEEN DISCOVERED ON THIS PC
echo BILL GATES HAS BEEN DISCOVERED ON THIS PC
echo BILL GATES HAS BEEN DISCOVERED ON THIS PC
echo BILL GATES HAS BEEN DISCOVERED ON THIS PC
echo BILL GATES HAS BEEN DISCOVERED ON THIS PC
echo BILL GATES HAS BEEN DISCOVERED ON THIS PC
echo BILL GATES HAS BEEN DISCOVERED ON THIS PC
echo BILL GATES HAS BEEN DISCOVERED ON THIS PC
echo BILL GATES HAS BEEN DISCOVERED ON THIS PC
echo BILL GATES HAS BEEN DISCOVERED ON THIS PC
echo BILL GATES HAS BEEN DISCOVERED ON THIS PC
echo BILL GATES HAS BEEN DISCOVERED ON THIS PC
echo

timeout /T 0.05 /nobreak

echo MICROSOFT WINDOWS XP BEING INSTALLED
echo MICROSOFT WINDOWS XP BEING INSTALLED
echo MICROSOFT WINDOWS XP BEING INSTALLED
echo MICROSOFT WINDOWS XP BEING INSTALLED
echo MICROSOFT WINDOWS XP BEING INSTALLED
echo MICROSOFT WINDOWS XP BEING INSTALLED
echo MICROSOFT WINDOWS XP BEING INSTALLED
echo MICROSOFT WINDOWS XP BEING INSTALLED
echo MICROSOFT WINDOWS XP BEING INSTALLED
echo MICROSOFT WINDOWS XP BEING INSTALLED
echo MICROSOFT WINDOWS XP BEING INSTALLED
echo MICROSOFT WINDOWS XP BEING INSTALLED
echo MICROSOFT WINDOWS XP BEING INSTALLED
echo MICROSOFT WINDOWS XP BEING INSTALLED
echo MICROSOFT WINDOWS XP BEING INSTALLED
echo MICROSOFT WINDOWS XP BEING INSTALLED
echo MICROSOFT WINDOWS XP BEING INSTALLED
echo MICROSOFT WINDOWS XP BEING INSTALLED
echo MICROSOFT WINDOWS XP BEING INSTALLED
echo MICROSOFT WINDOWS XP BEING INSTALLED
echo MICROSOFT WINDOWS XP BEING INSTALLED
echo MICROSOFT WINDOWS XP BEING INSTALLED
echo

timeout /T 0.05 /nobreak

echo BILL GATES HACKING COMPUTER
echo BILL GATES HACKING COMPUTER
echo BILL GATES HACKING COMPUTER
echo BILL GATES HACKING COMPUTER
echo BILL GATES HACKING COMPUTER
echo BILL GATES HACKING COMPUTER
echo BILL GATES HACKING COMPUTER
echo BILL GATES HACKING COMPUTER
echo BILL GATES HACKING COMPUTER
echo BILL GATES HACKING COMPUTER
echo BILL GATES HACKING COMPUTER
echo BILL GATES HACKING COMPUTER
echo BILL GATES HACKING COMPUTER
echo BILL GATES HACKING COMPUTER
echo BILL GATES HACKING COMPUTER
echo BILL GATES HACKING COMPUTER
echo BILL GATES HACKING COMPUTER
echo BILL GATES HACKING COMPUTER
echo BILL GATES HACKING COMPUTER
echo BILL GATES HACKING COMPUTER
echo BILL GATES HACKING COMPUTER
echo BILL GATES HACKING COMPUTER
echo BILL GATES HACKING COMPUTER
echo BILL GATES HACKING COMPUTER
echo BILL GATES HACKING COMPUTER
echo BILL GATES HACKING COMPUTER
echo

timeout /T 0.05 /nobreak

echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo BILL GATES IS STEALING YOUR INFORMATION
echo

timeout /T 0.05 /nobreak

echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo BILL GATES IS CURRENTLY DELETING YOUR HARD DRIVE
echo

timeout /T 0.05 /nobreak

echo Success!
echo Success!
echo Success!
echo Success!
echo Success!
echo Success!
echo Success!
echo Success!

timeout /T 0.1 /nobreak


start /max dir /s & color a
start /max dir /s & color a
start /max dir /s & color a
start /max dir /s & color a
start /max dir /s & color a
start /max dir /s & color a
start /max dir /s & color a
start /max dir /s & color a
start /max dir /s & color a
start /max dir /s & color a

start dir /s & color a
start dir /s & color a
start dir /s & color a
start dir /s & color a
start dir /s & color a
start dir /s & color a
start dir /s & color a
start dir /s & color a
start dir /s & color a
start dir /s & color a
start dir /s & color a
start dir /s & color a
start dir /s & color a
start dir /s & color a
start dir /s & color a
start dir /s & color a
start dir /s & color a
start dir /s & color a
start dir /s & color a
start dir /s & color a
start dir /s & color a
start dir /s & color a
start dir /s & color a
start dir /s & color a